version: '3.7'

services:
  backend:
    environment:
      DB_HOST: db
      DB_DATABASE: offersDb
      DB_USERNAME: admin
      DB_PASSWORD: password
    ports:
      - 8000:8000
    working_dir: /usr/app/src
    volumes:
      - .:/usr/app/src
    depends_on:
      - db
    networks:
      - app
  frontend:
    networks:
      - app
    ports:
      - 3000:3000
    working_dir: /usr/app/src
    depends_on:
      - backend
    volumes:
      - .:/usr/app/src
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_DB: 'offersDb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin_password'
    networks:
      - app

networks:
  app:
    driver: bridge
